### ISSUE TITLE
[BUG] Uploading profile picture does not work in the server side

### ISSUE THREAD

**Issue by amitripshtos** [frontegg/frontegg-react#102]
**Describe the bug**
I can not upload a profile picture because of error 500 from the server.
I get as a response:
{"statusCode":500,"message":"failed to upload profile image","error":"Internal Server Error"}

**To Reproduce**
1. Go to profile page
2. Upload new profile image
3. Click update profile

**Additional context**
Frontegg-react 1.6.0

**Comment by frontegg-david** [comment]
@amitripshtos what is the version of @frontegg/client  in your backend?

**Comment by amitripshtos** [comment]
I'm using the latest python-sdk.

**Comment by frontegg-david** [comment]
> I'm using the latest python-sdk.
> @amitripshtos <https://github.com/amitripshtos>.

this i

**Comment by aviadmizrachi** [comment]
@amitripshtos I am not sure this is supported on an on-prem installation. Need to check

**Comment by aviadmizrachi** [comment]
This is not supported on hybrid envs. 
Closing this for now
