### ISSUE TITLE
Issue with redirection from /oauth/callback

### ISSUE THREAD

**Issue by MaxDNG** [frontegg/frontegg-react#1126]
Hi all, I am trying to integrate the package in my application and I have a problem with the final redirection.

I have followed the steps for [hosted login integration](https://docs.frontegg.com/docs/react-hosted-login-guide). Everything works fine until the redirection. Although I am eventually redirected to `http://localhost:3000/oauth/callback` then I see the frontegg loader (the 3 bars) which hang forever.

What is supposed to happen then? How can I redirect the user from /oauth/callback to another path?

What I've tried so far:
- setting a redirect_uri query param
- trying to catch the route in react-router but it seems frontegg provider catches it first

**Comment by yuvalotem1** [comment]
Hey, @MaxDNG, do you have a reproduction for that issue?
Ensure you have `hostedLoginBox={true}` in your `FronteggProvider` options.
Also enable hosted login in frontegg portal - https://portal.frontegg.com/development/authentication/hosted
