### ISSUE TITLE
[BUG] loadUserOnFirstLoad prevents full redirect to login page

### ISSUE THREAD

**Issue by kadosh1000** [frontegg/frontegg-react#1172]
**Describe the bug**
I am integrating Frontegg hosted login into our React app, using @frontegg/react v7.0.1 (latest).
The main issue is with the `loadUserOnFirstLoad` option.

When set to `true`, `loginWithRedirect` not redirects correctly, it is redirecting to `localhost:3000/account/login` and not continuing to the frontegg domain. This view, when inserting the email only shows an error:

![image](https://github.com/user-attachments/assets/152742a6-5bfd-4f8b-a4eb-5d2ab514869c)

When setting `loadUserOnFirstLoad` to `false`, the redirect works well, but then on every refresh, the user goes through all redirects every time even though they are already connected.

Here is the code I am using:

    const AuthProvider: React.FC<{ children: ReactNode }> = ({children}) => {        
        const [authContextOptions, setAuthContextOptions] = useState<ContextOptions | null>(null)
        
        useEffect(()=>{
            async function getAppSettings(){
                const settings = await getSettings()
                setAuthContextOptions({
                    baseUrl: settings.frontegg.base_url,
                    clientId: settings.frontegg.client_id
                })
            }

            getAppSettings()
        },[])

        return authContextOptions ? (
            <FronteggProvider
                contextOptions={authContextOptions}
                hostedLoginBox={true}
                authOptions={{
                    // TODO: setting loadUserOnFirstLoad to false fixes redirect issue, 
                    // but causes every refresh to go through all redirects
                    hostedLoginOptions: {loadUserOnFirstLoad : false}
                }}
            >
                {children}
            </FronteggProvider>
        ) : <></>;
    };

    export default AuthProvider;

**Expected behavior**
Setting `loadUserOnFirstLoad` to `true`, `loginWithRedirect` should handled correctly redirecting the user to login page under "xxx.frontegg.com" domain.

**Comment by kadosh1000** [comment]
@aviadmizrachi @frontegg-david do you have any clues regarding that? It is currently holding us from releasing with it

**Comment by frontegg-david** [comment]
Hi @kadosh1000,

Could you please provide details on how you are calling the loginWithRedirect method?

**Comment by kadosh1000** [comment]
Hi @frontegg-david, sure, 
basically doing it just as pointed in the docs, having a `useEffect` dependent on `isAuthenticated`.
here is my app.tsx:

```
const App = () => {
    const {isAuthenticated} = useAuth();
    const user = useAuthUser();
    const tenant = useTenantsState();
    const loginWithRedirect = useLoginWithRedirect();
    const {dispatchUserAction} = useLoggedInUser();

    useEffect(() => {
        if (!isAuthenticated) {
            loginWithRedirect();
        }
    }, [isAuthenticated, loginWithRedirect]);

    useEffect(() => {
        if (isAuthenticated && tenant.activeTenant) {
            dispatchUserAction(
                saveLoggedInUser({
                    name: user.name,
                    profilePictureUrl: user.profilePictureUrl,
                    email: user.email,
                    organization: tenant.activeTenant.name,
                })
            );
        }
    }, [isAuthenticated, user, tenant, dispatchUserAction]);

    return (
        isAuthenticated ? (
            <Routes>
                
            </Routes>
        ) : (<></>)
    );
};
```

**Comment by frontegg-david** [comment]
Hi @kadosh1000 

Thank you for the details you've provided.

As I see it, the `useAuthUser` hook is not supported in hosted login mode, which causes the user to be redirected to `/account/login` if the user is `null`. Could you please try using `useAuthUserOrNull` instead? This issue will be fixed in the next version.

Additionally, I want to mention that you should not use `useAuthUser` without ensuring the user is authenticated, as this hook returns a non-nullable user. If the user is not authenticated, it will redirect them to the login page. In your case, using `useAuthUser` along with `loginWithRedirect` may not work due to a race condition between the `useEffect` for `loginWithRedirect` and the navigation triggered because the user is `null` in the `useAuthUser` hook.

Here’s how you could refactor your code:

```typescript
const App = () => {
    const { isAuthenticated } = useAuth();
    const user = useAuthUserOrNull();  // Use `useAuthUserOrNull` instead
    const tenant = useTenantsState();
    const loginWithRedirect = useLoginWithRedirect();
    const { dispatchUserAction } = useLoggedInUser();

    useEffect(() => {
        if (!isAuthenticated) {
            loginWithRedirect();
        }
    }, [isAuthenticated, loginWithRedirect]);

    useEffect(() => {
        if (isAuthenticated && user && tenant.activeTenant) {  // Add check for `user`
            dispatchUserAction(
                saveLoggedInUser({
                    name: user.name,
                    profilePictureUrl: user.profilePictureUrl,
                    email: user.email,
                    organization: tenant.activeTenant.name,
                })
            );
        }
    }, [isAuthenticated, user, tenant, dispatchUserAction]);

    return isAuthenticated ? (
        <Routes>
            {/* Your routes go here */}
        </Routes>
    ) : (
        <></>
    );
};
```

Let me know if this helps, and feel free to reach out if you need further assistance.

**Comment by kadosh1000** [comment]
Thanks @frontegg-david it seems to solve my issue.
Completely missed that `useAuthUser` was meant for embedded login and doing redirects automatically.
