### ISSUE TITLE
[BUG] Console errors on Team Management and Login pages

### ISSUE THREAD

**Issue by netamona** [frontegg/frontegg-react#119]
**Describe the bug**
Console errors on team management and login pages.

**To Reproduce**
1. Go to the above pages. 
2. Open the console and click the error tab.
3. See the errors.

**Expected behavior**
Remove any errors and warnings from the console.

**Screenshots**
<img width="1440" alt="Screen Shot 2020-11-25 at 11 41 13" src="https://user-images.githubusercontent.com/62515518/100209967-21a0c300-2f13-11eb-8bcc-d2cb66aadd5f.png">

<img width="1440" alt="Screen Shot 2020-11-25 at 11 41 39" src="https://user-images.githubusercontent.com/62515518/100210038-2feedf00-2f13-11eb-8530-b9a00a25cd7e.png">

**Comment by netamona** [comment]
@frontegg-david Why was this issue closed? The errors are still showing on v1.11.1.

**Comment by frontegg-david** [comment]
The errors are still showing on `v1.11.1` #138
