### ISSUE TITLE
[BUG] New version causes breaking

### ISSUE THREAD

**Issue by netamona** [frontegg/frontegg-react#129]
**Describe the bug**
When updating react-auth with npm install we get the following errors:
Attempted import error: 'MenuItem' is not exported from '@frontegg/react-core'.
Attempted import error: 'SocialLoginsProviders' is not exported from '@frontegg/rest-api'.

**To Reproduce**
1. install frontegg/react-auth v.1.10.0

**Expected behavior**
No breaking

**Screenshots**
![Screen Shot 2020-11-29 at 18 20 09](https://user-images.githubusercontent.com/62515518/100547454-8770b000-326f-11eb-93cc-a284c5c968cc.png)

**Comment by frontegg-david** [comment]
Please align all the npm packages to the same version.
Core and Auth packages should be updated to 1.10.0

**Comment by frontegg-david** [comment]
@netamona

**Comment by netamona** [comment]
When updating the packages I get this error: 
![Screen Shot 2020-11-30 at 11 27 13](https://user-images.githubusercontent.com/62515518/100591847-0234dc00-32ff-11eb-8652-277dd5eb1bed.png)
 
my package.json:
<img width="459" alt="Screen Shot 2020-11-30 at 11 27 53" src="https://user-images.githubusercontent.com/62515518/100591913-18db3300-32ff-11eb-89a1-48cf9a85f21d.png">
