### ISSUE TITLE
[FEATURE] Allow updating API Tokens table headers

### ISSUE THREAD

**Issue by slope-hassaan-ali** [frontegg/frontegg-react#225]
Currently it's possible to update much of the UI via i18next. One part that isn't customizable is the API Tokens table headers found here: https://github.com/frontegg/frontegg-react/blob/7a5f7608d83688291171b569aafacc6aada9593a/packages/auth/src/ApiTokens/constants.ts#L1-L62

It would be great to be able to customize this part of the UI as well.

**Comment by slope-hassaan-ali** [comment]
Accidentally left the "bug" label on :)

**Comment by aviadmizrachi** [comment]
This one was fixed
Allowed by adding prop on the column
