### ISSUE TITLE
[BUG] Package.json module property points to non-existent file

### ISSUE THREAD

**Issue by sdemjanenko** [frontegg/frontegg-react#351]
When building an app using snowpack I hit the error:

```
[snowpack] Cannot find module '/Users/stephen/Code/permiso/arbiter/frontend/node_modules/@frontegg/react-hooks/index.esm.js' from '/Users/stephen/Code/permiso/arbiter/frontend/node_modules/snowpack/lib'
```

Upon inspecting the package.json file in `node_modules/@frontegg/react-hooks` I noticed that the module key points to `index.esm.js` but that file does not exist in `node_modules/@frontegg/react-hooks`.

**Comment by frontegg-david** [comment]
@sdemjanenko upgrade to react-hooks 3.3.0
