### ISSUE TITLE
[BUG] GithubIcon.tsx text should be "GitHub", not "Github"

### ISSUE THREAD

**Issue by JLDLaughlin** [frontegg/frontegg-react#726]
**Describe the bug**
The Frontegg GitHub SSO button reads "Github" when it should be "GitHub".

**To Reproduce**
Check [GithubIcon.tsx](https://github.com/frontegg/frontegg-react/blob/676c928395833e014b8d4cb3237868f0787432c4/packages/auth/src/SocialLogins/GithubLogin/GithubIcon.tsx)!

**Expected behavior**
Change to "GitHub".

**Screenshots**
![](https://user-images.githubusercontent.com/5766027/167047812-0f1067cb-7268-4dae-ae5d-c68fa9590c55.png)

**Additional context**

**Comment by JLDLaughlin** [comment]
hey team, any update on this change?

**Comment by rotemzif1** [comment]
@JLDLaughlin Hey! thanks for the feedback I will push a fix today

**Comment by aviadmizrachi** [comment]
Fixed on latest version
