### ISSUE TITLE
[BUG] FronteggProvider missing withRouter type definition

### ISSUE THREAD

**Issue by sdemjanenko** [frontegg/frontegg-react#86]
**Describe the bug**
In v1.2.0
```
<FronteggProvider
  withRouter
/>
```
compiled in Typescript. In v1.3.0 this hits
```
Property 'withRouter' does not exist on type 'IntrinsicAttributes & FeProviderProps & { children?: ReactNode; }'.
```

**Comment by frontegg-david** [comment]
Hi @sdemjanenko ,
As you can see in this [Pull Request](https://github.com/frontegg/frontegg-react/pull/81/files#diff-82547d9db51c4dc2bac65ca825b9b700f7db18966776859ef719ccf8960466a4) that we have removed the deprecated props `withRouter` now we are trying to resolve the vendor react-router and if not presented we will inject it before rendering the FronteggProvider.
