### ISSUE TITLE
Unable to upload a profile image

### ISSUE THREAD

**Issue by sdemjanenko** [frontegg/frontegg-react#87]
It appears that the My Profile page displays an image but it doesn't appear that I can upload the image.

![image](https://user-images.githubusercontent.com/234437/98286713-41b71500-1f59-11eb-8a4e-9ca5a6a53eba.png)

**Comment by frontegg-david** [comment]
We are currently support gravatar profile image by logged in user's email.
Added to the list of feature requests.
