### ISSUE TITLE
[BUG] Local React builds take much longer with @frontegg/react package

### ISSUE THREAD

**Issue by map-r** [frontegg/frontegg-react#911]
**Describe the bug**
Comparing two states of the app development, first one is without @frontegg packages imported nor used in the code, second is with the @frontegg/react added to project and imported in code, with LoginBox used.
The LoginBox is used in an embedded configuration.

- App is created in create-react-app,
- React is "17.0.2",
- @frontegg/react is "5.0.15"

**To Reproduce**
1. start the local development server
2. apply any insignificant change to code (e.g. insert a comment or console.log)
3. observe the amount of time to rebuild/ hot reload the app in the console
4. Time to reload takes a lot of time (approx. 11+ secs)

**Expected behavior**
There should be no major increases in reload time with Frontegg, I think that ~1-2 secs extra could be acceptable.

**Additional context**
In case you need additional info, I'm happy to help

**Comment by roydfrontegg** [comment]
User reported It is working after changing minor package versions \ fresh to the development builds.
