### ISSUE TITLE
Question: How to redirect to Login page after session timeout

### ISSUE THREAD

**Issue by ranbackslash** [frontegg/frontegg-react#937]
Hello, 
In my app, when frontegg session ends, a blank page is currently being displayed to the user. 
The expected behaviour is that the user will be redirected to frontegg login page so I wanted to know if the SDK provides a way of doing it?

Thanks.

**Comment by MashaPav** [comment]
Hi there, 

Can you please send us an email with the details of your implementation to support@frontegg.com (hosted / embedded, version of frontegg/react)? Otherwise, you can also join our community slack and the team will help you out there with any questions.
