### ISSUE TITLE
[BUG] how should i integrate with RouterProvider of React Router V6?

### ISSUE THREAD

**Issue by KaynRonan** [frontegg/frontegg-react#980]
**Describe the bug**
 i integrate with RouterProvider of React Router V6, and it report an error: You cannot render a <Router> inside another <Router>. You should never have more than one in your app.

**To Reproduce**

```javascript
ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <FronteggProvider contextOptions={contextOptions} hostedLoginBox={true} authOptions={authOptions}>
      <RouterProvider router={createBrowserRouter(Routes)}></RouterProvider>
    </FronteggProvider>
  </React.StrictMode>,
);
```

**Screenshots**
<img width="903" alt="image" src="https://github.com/frontegg/frontegg-react/assets/132924315/c73e16c7-4961-40b9-849e-11322e5907aa">

**Comment by MashaPav** [comment]
Hi @KaynRonan! 

Can you please email us at `support@frontegg.com` with the details of your package.json or send a message in one of our [community slack channels](https://join.slack.com/t/frontegg-community/shared_invite/zt-e1oxi1vn-SZErBZcwHcbgj4vrwRIp5A)? 

We will be happy to help you set this up via one of these communication channels.

**Comment by KaynRonan** [comment]
> Hi @KaynRonan!
> 
> Can you please email us at `support@frontegg.com` with the details of your package.json or send a message in one of our [community slack channels](https://join.slack.com/t/frontegg-community/shared_invite/zt-e1oxi1vn-SZErBZcwHcbgj4vrwRIp5A)?
> 
> We will be happy to help you set this up via one of these communication channels.

maybe you can try a demo with react-router v6，and then you can improve you docs tell developers how can we use frontegg with react-router v6. 
your document does not provide any explanation about the react router, it simply refers to a <App/> component internally

**Comment by MashaPav** [comment]
Thanks for the feedback @KaynRonan, we are actively working on improving our documentation and we'll take that into consideration! In case you'll need any help in the meantime, feel free to send us a message via one of the support channels.

**Comment by MashaPav** [comment]
The full solution for using react router v6 with `@frontegg/react` is described here - https://support.frontegg.com/hc/en-us/articles/11571585765789-How-to-use-React-Router-v6-with-Frontegg-

**Comment by mattotodd** [comment]
thx @MashaPav that article was super helper
